### PR TITLE
Support latest Pry::BondCompleter rename start -> setup

### PR DESCRIPTION
**Pull request by matrinox**
Doesn't work with latest

### CODE REVIEW

**Comment by liaden** [comment]
@matrinox Are you still interested in this?

**Comment by matrinox** [comment]
@liaden this is so long ago that I don't remember what it was for ><. Go ahead and delete it if you want

**Comment by garymh** [comment]
I think this is still an issue! Using the latest I get: 
```
Error loading ~/.pryrc: undefined method `start' for Pry::BondCompleter:Class
/Users/gary/.asdf/installs/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/pry-coolline-0.2.6/lib/pry-coolline.rb:24:in `<main>'
```

**Comment by liaden** [comment]
@garymh Thanks for confirming. Will take a look sometime next week, ideally.

**Pull request closed without merging**
